<?php

namespace App\Enums;

enum MutationStatus: string
{
    case DISTRIBUTION_COMPLETED = 'DISTRIBUTION_COMPLETED';
    case DISTRIBUTION_CANCELED = 'DISTRIBUTION_CANCELED';
    case DISTRIBUTION_REJECTED = 'DISTRIBUTION_REJECTED';

    case TRANSFER_COMPLETED = 'TRANSFER_COMPLETED';
    case TRANSFER_CANCELED = 'TRANSFER_CANCELED';
    case TRANSFER_REJECTED = 'TRANSFER_REJECTED';

    case RESTOCK_COMPLETED = 'RESTOCK_COMPLETED';
    case RESTOCK_CANCELED = 'RESTOCK_CANCELED';
    case RESTOCK_REJECTED = 'RESTOCK_REJECTED';

    case RETURN_COMPLETED = 'RETURN_COMPLETED';
    case RETURN_CANCELED = 'RETURN_CANCELED';
    case RETURN_REJECTED = 'RETURN_REJECTED';

    case RECEIVE_COMPLETED = 'RECEIVE_COMPLETED';
    case RECEIVE_CANCELED = 'RECEIVE_CANCELED';
    case RECEIVE_REJECTED = 'RECEIVE_REJECTED';
}
